"use client";

import Link from "next/link";
import { Activity, ArrowUpRight, HeartPulse, LockKeyhole, Microscope, ShieldCheck } from "lucide-react";
import { SignInButton, SignUpButton, UserButton } from "@clerk/nextjs";

function Brand() {
  return <Link className="clinic-brand" href="/"><span className="clinic-brand-mark"><HeartPulse size={19} /></span><span>cardio<span>fusion</span></span></Link>;
}

export function Landing({ authenticated = false }: { authenticated?: boolean }) {
  const clerkReady = Boolean(process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY);
  const actions = authenticated ? <><Link className="clinic-workspace-link" href="/dashboard">Open workspace <ArrowUpRight size={16} /></Link><UserButton afterSignOutUrl="/" /></> : <>{clerkReady ? <SignInButton mode="modal"><button className="clinic-signin">Sign in</button></SignInButton> : <button className="clinic-signin">Sign in</button>}{clerkReady ? <SignUpButton mode="modal"><button className="clinic-header-cta">Create workspace <ArrowUpRight size={15} /></button></SignUpButton> : <button className="clinic-header-cta">Create workspace <ArrowUpRight size={15} /></button>}</>;

  return <main className="clinic-home">
    <header className="clinic-nav"><Brand /><nav><Link href="/about">About</Link><Link href="/contact">Contact</Link></nav><div className="clinic-nav-actions">{actions}</div></header>
    <section className="clinic-hero"><div className="clinic-hero-copy"><div className="clinic-kicker"><span /> CARDIOVASCULAR EVIDENCE, IN CONTEXT</div><h1>Better questions<br /><i>start with</i><br />better evidence.</h1><p className="clinic-lede">CardioFusion brings blood work, ECG signals, and echo video into one calm, private workspace for understanding what the heart is saying.</p><div className="clinic-hero-actions">{authenticated ? <Link className="clinic-primary" href="/dashboard">Open your workspace <ArrowUpRight size={17} /></Link> : clerkReady ? <SignUpButton mode="modal"><button className="clinic-primary">Create your workspace <ArrowUpRight size={17} /></button></SignUpButton> : <button className="clinic-primary">Create your workspace <ArrowUpRight size={17} /></button>}<span><LockKeyhole size={15} /> Private by default</span></div></div><div className="clinical-board" aria-label="CardioFusion evidence overview"><div className="board-top"><span>CF / EVIDENCE DESK</span><span className="board-live"><i /> READY TO REVIEW</span></div><div className="board-pulse"><div className="pulse-label"><HeartPulse size={18} /><span>Signal overview</span></div><svg viewBox="0 0 560 150" preserveAspectRatio="none" aria-hidden="true"><path d="M0 82 H72 L89 82 L104 35 L120 124 L139 82 H195 L207 82 L220 64 L232 96 L244 82 H310 L326 82 L339 23 L356 132 L374 82 H430 L443 82 L455 58 L469 105 L483 82 H560" /></svg><div className="pulse-time"><span>00:00</span><span>00:30</span><span>01:00</span></div></div><div className="board-cards"><div><span className="board-card-icon"><Microscope size={17} /></span><small>Clinical</small><strong>Blood work</strong><em>Ready</em></div><div><span className="board-card-icon coral"><Activity size={17} /></span><small>Electrical</small><strong>ECG signal</strong><em>Ready</em></div><div><span className="board-card-icon yellow"><HeartPulse size={17} /></span><small>Functional</small><strong>Echo study</strong><em>Optional</em></div></div><div className="board-foot"><span><ShieldCheck size={14} /> Three views, one considered picture</span><b>01</b></div></div></section>
    <section className="clinic-principles"><div className="principle-intro"><span className="clinic-kicker"><span /> HOW IT WORKS</span><h2>One heart.<br /><i>Several signals.</i></h2></div><div className="principle-list"><article><b>01</b><div><h3>Bring what you have</h3><p>Upload a report, ECG, or echo study. The picture can grow over time.</p></div></article><article><b>02</b><div><h3>Keep signals honest</h3><p>Each modality stays distinct, with uncertainty and missing evidence in view.</p></div></article><article><b>03</b><div><h3>Leave with a question</h3><p>Use the resulting context to have a more informed conversation with your care team.</p></div></article></div></section>
    <footer className="clinic-footer"><Brand /><span>For understanding, not diagnosis.</span><Link href="/contact">Get in touch <ArrowUpRight size={14} /></Link></footer>
  </main>;
}
