"use client";

import { useEffect, useMemo, useState } from "react";
import { usePathname, useRouter } from "next/navigation";
import Link from "next/link";
import { Activity, ArrowUpRight, Check, ChevronRight, FileHeart, FlaskConical, HeartPulse, History, LockKeyhole, Menu, Settings, Sparkles, UploadCloud, Video, X } from "lucide-react";
import { UserButton, useAuth, useUser } from "@clerk/nextjs";

type Risk = { display_name?: string; risk: number | null };
type Report = { id: string; label: string; status: string; modalities: string[]; result?: { disease_results?: Risk[]; modalities?: Record<string, { status?: string; available?: boolean }> }; recommendations?: { source?: string; summary?: string; recommendations?: string[] }; createdAt: string };
type Profile = { phone: string; address: string; username: string };
const apiUrl = process.env.NEXT_PUBLIC_SERVER_URL ?? "http://localhost:4000";
let reportsCache: { userId: string; reports: Report[] } | null = null;

function apiFetch(path: string, token: string, options: RequestInit = {}) { return fetch(`${apiUrl}${path}`, { ...options, headers: { ...(options.headers ?? {}), Authorization: `Bearer ${token}` } }); }
function Brand() { return <Link className="brand" href="/"><span className="brand-mark"><Activity size={18} /></span><span>cardio<span>fusion</span></span></Link>; }
function displayName(user: ReturnType<typeof useUser>["user"]) { if (!user) return "Your workspace"; const name = [user.firstName, user.lastName].filter(Boolean).join(" "); return name || user.fullName || user.username || user.emailAddresses[0]?.emailAddress?.split("@")[0] || "Your workspace"; }

const navItems = [
  ["/dashboard", "Overview", Activity],
  ["/dashboard/upload", "New assessment", UploadCloud],
  ["/dashboard/history", "History", History],
  ["/dashboard/analysis", "Analysis", HeartPulse],
  ["/dashboard/settings", "Settings", Settings],
] as const;

export function Workspace() {
  const { isLoaded, isSignedIn, getToken } = useAuth();
  const { user } = useUser();
  const pathname = usePathname();
  const router = useRouter();
  const [reports, setReports] = useState<Report[]>([]);
  const [selectedReportId, setSelectedReportId] = useState<string | null>(null);
  const [profile, setProfile] = useState<Profile>({ phone: "", address: "", username: "" });
  const [files, setFiles] = useState<Record<string, File | null>>({ biomarkers: null, ecg: null, echo: null });
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState("");
  const name = displayName(user);
  const activePath = pathname === "/" ? "/dashboard" : pathname;
  const active = reports[0];
  const selected = reports.find((report) => report.id === selectedReportId) ?? active;
  const latestRisk = active?.result?.disease_results?.filter((item) => item.risk !== null).slice(0, 2) ?? [];
  const chartPoints = useMemo(() => reports.slice(0, 8).reverse().map((report, index) => ({ x: 10 + index * 12, y: 76 - ((report.result?.disease_results?.find((item) => item.risk !== null)?.risk ?? .2) * 55) })), [reports]);

  async function load() { const token = await getToken(); if (!token || !user) return; if (reportsCache?.userId === user.id) setReports(reportsCache.reports); const reportRequest = reportsCache?.userId === user.id ? null : apiFetch("/api/reports", token); const profileRequest = pathname === "/dashboard/settings" ? apiFetch("/api/profile", token) : null; const [reportResponse, profileResponse] = await Promise.all([reportRequest, profileRequest]); if (reportResponse?.ok) { const nextReports = (await reportResponse.json()).reports; reportsCache = { userId: user.id, reports: nextReports }; setReports(nextReports); } if (profileResponse?.ok) { const data = await profileResponse.json(); setProfile({ phone: data.user.phone ?? "", address: data.user.address ?? "", username: data.user.username ?? "" }); } }
  // Hydrate the authenticated workspace from the API after Clerk resolves.
  // eslint-disable-next-line react-hooks/set-state-in-effect, react-hooks/exhaustive-deps
  useEffect(() => { if (isSignedIn) void load(); }, [isSignedIn, user]);
  async function submitReport() { const token = await getToken(); if (!token) return; const chosen = Object.entries(files).filter(([, file]) => file); if (!chosen.length) { setMessage("Choose at least one report first."); return; } setBusy(true); setMessage("Uploading and reading your evidence..."); const form = new FormData(); chosen.forEach(([key, file]) => form.append(key, file!)); form.append("label", "Cardiovascular assessment"); const response = await apiFetch("/api/reports", token, { method: "POST", body: form }); setBusy(false); if (response.ok) { reportsCache = null; setFiles({ biomarkers: null, ecg: null, echo: null }); setMessage("Assessment complete. Your evidence is ready."); await load(); router.push("/dashboard"); } else setMessage("We could not complete this assessment. Check that the service is running."); }
  async function saveProfile(event: React.FormEvent) { event.preventDefault(); const token = await getToken(); if (!token) return; await apiFetch("/api/profile", token, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(profile) }); setMessage("Settings saved."); }

  if (!isLoaded) return <div className="loading-screen">Preparing your private workspace...</div>;
  if (!isSignedIn) return <div className="loading-screen">Sign in to open this workspace.</div>;
  const section = activePath === "/dashboard/upload" ? "upload" : activePath === "/dashboard/history" ? "history" : activePath === "/dashboard/settings" ? "settings" : activePath === "/dashboard/analysis" ? "analysis" : "overview";
  const heading = section === "overview" ? `Good to see you, ${name}.` : section === "upload" ? "Start an assessment." : section === "history" ? "Your history." : section === "analysis" ? "Analysis." : "Settings.";
  const eyebrow = section === "overview" ? "Your evidence desk" : section === "upload" ? "Add evidence" : section === "history" ? "A record over time" : section === "analysis" ? "A closer look" : "Your details";

  return <main className="workspace"><aside className="sidebar"><Brand /><div className="sidebar-user"><div className="avatar">{name[0]?.toUpperCase()}</div><div><b>{name}</b><small>Private account</small></div></div><nav className="side-nav">{navItems.map(([href, label, Icon]) => <Link className={activePath === href ? "active" : ""} href={href} key={href}><Icon size={17} /> {label}{label === "History" && <span>{reports.length}</span>}</Link>)}</nav><div className="sidebar-bottom"><div className="privacy-note"><LockKeyhole size={15} /><span>Your data stays yours.<br /><small>Private by default.</small></span></div><UserButton afterSignOutUrl="/" /></div></aside><section className="workspace-main"><header className="workspace-header"><div><div className="eyebrow">{eyebrow}</div><h1 className="serif">{heading}</h1></div><button className="mobile-menu" aria-label="Open navigation"><Menu size={20} /></button></header>{message && <div className="toast"><Check size={15} />{message}<button onClick={() => setMessage("")} aria-label="Dismiss"><X size={14} /></button></div>}{section === "overview" && <Overview active={active} latestRisk={latestRisk} chartPoints={chartPoints} selectedReport={selected} onSelectReport={setSelectedReportId} onNew={() => router.push("/dashboard/upload")} />}{section === "upload" && <UploadPanel files={files} setFiles={setFiles} busy={busy} submit={submitReport} />}{section === "history" && <HistoryPanel reports={reports} onSelect={(id) => { setSelectedReportId(id); router.push("/dashboard/analysis"); }} />}{section === "analysis" && <AnalysisPanel report={selected} />}{section === "settings" && <SettingsPanel profile={profile} setProfile={setProfile} save={saveProfile} />}</section></main>;
}

function Overview({ active, latestRisk, chartPoints, selectedReport, onSelectReport, onNew }: { active?: Report; latestRisk: Risk[]; chartPoints: Array<{ x: number; y: number }>; selectedReport?: Report; onSelectReport: (id: string) => void; onNew: () => void }) { const report = selectedReport ?? active; return <div className="dashboard-content fade-up"><div className="overview-top"><div><span className="eyebrow">{report && report.id !== active?.id ? "Selected assessment" : "Latest assessment"}</span><h2 className="serif">{report ? report.label : "Your first read is waiting."}</h2><p>{report ? new Date(report.createdAt).toLocaleDateString("en", { month: "long", day: "numeric", year: "numeric" }) : "Bring whatever evidence you have. We will keep the picture honest."}</p></div><button className="coral-button" onClick={onNew}><UploadCloud size={16} /> Add evidence</button></div><div className="metric-grid"><div className="metric-card wide"><div className="metric-head"><span>Evidence confidence</span><Sparkles size={17} /></div><strong>{report ? "Review ready" : "No assessment yet"}</strong><p>{report ? `${report.modalities.length} modality${report.modalities.length === 1 ? "" : "ies"} in this read` : "Start with one report or scan."}</p><div className="confidence-bar"><i style={{ width: report ? "72%" : "8%" }} /></div></div>{latestRisk.map((item) => <div className="metric-card" key={item.display_name}><span>{item.display_name}</span><strong>{item.risk !== null ? `${Math.round(item.risk * 100)}%` : "-"}</strong><small>model-estimated risk</small></div>)}</div><div className="detail-grid"><div className="results-panel"><div className="panel-heading"><div><span className="eyebrow">Risk signals</span><h3 className="serif">What the models noticed</h3></div><HeartPulse size={21} /></div>{report?.result?.disease_results?.filter((item) => item.risk !== null).slice(0, 4).map((item) => <div className="result-row" key={item.display_name}><span>{item.display_name}</span><b>{Math.round((item.risk ?? 0) * 100)}%</b></div>) ?? <p className="empty-copy">Upload evidence to see calibrated signals here.</p>}</div><div className="context-panel"><div className="panel-heading"><div><span className="eyebrow">Trajectory</span><h3 className="serif">Across your reads</h3></div><Activity size={20} /></div><svg className="risk-chart" viewBox="0 0 100 86" role="img" aria-label="Risk trend">{chartPoints.length > 1 && <polyline points={chartPoints.map((point) => `${point.x},${point.y}`).join(" ")} fill="none" stroke="currentColor" strokeWidth="1.5" />}</svg><button className="text-link" onClick={() => report && onSelectReport(report.id)}>Open selected analysis <ChevronRight size={16} /></button></div></div></div>; }
function UploadPanel({ files, setFiles, busy, submit }: { files: Record<string, File | null>; setFiles: React.Dispatch<React.SetStateAction<Record<string, File | null>>>; busy: boolean; submit: () => void }) { const inputs = [{ key: "biomarkers", label: "Blood / serum", hint: "PDF, PNG or DICOM", icon: <FlaskConical size={21} /> }, { key: "ecg", label: "ECG", hint: "Image, PDF or DICOM", icon: <Activity size={21} /> }, { key: "echo", label: "Echo video", hint: "AVI, MP4 or DICOM", icon: <Video size={21} /> }]; return <div className="dashboard-content fade-up"><div className="upload-intro"><p>Upload one or more pieces of evidence. Missing modalities remain visible instead of becoming assumptions.</p><span><LockKeyhole size={15} /> Encrypted in transit</span></div><div className="upload-grid">{inputs.map((input) => <label className={`upload-tile ${files[input.key] ? "chosen" : ""}`} key={input.key}>{input.icon}<b>{input.label}</b><small>{files[input.key]?.name ?? input.hint}</small>{files[input.key] ? <Check className="upload-check" size={18} /> : <UploadCloud className="upload-arrow" size={18} />}<input type="file" accept={input.key === "echo" ? ".avi,.mp4,.dcm" : ".pdf,.png,.jpg,.jpeg,.dcm"} onChange={(event) => setFiles((current) => ({ ...current, [input.key]: event.target.files?.[0] ?? null }))} /></label>)}</div><div className="upload-footer"><span>Files are sent to the analysis service only when you begin.</span><button className="coral-button" onClick={submit} disabled={busy}>{busy ? "Reading..." : "Begin assessment"} <ArrowUpRight size={16} /></button></div></div>; }
function HistoryPanel({ reports, onSelect }: { reports: Report[]; onSelect: (id: string) => void }) { return <div className="dashboard-content fade-up"><div className="history-list">{reports.length ? reports.map((report) => <button className="history-row" key={report.id} onClick={() => onSelect(report.id)}><div className="report-icon"><FileHeart size={18} /></div><div className="history-main"><b>{report.label}</b><span>{new Date(report.createdAt).toLocaleDateString()} · {report.modalities.join(" · ")}</span></div><span className={`history-status ${report.status.toLowerCase()}`}>{report.status.toLowerCase()}</span><ChevronRight size={17} /></button>) : <div className="empty-state"><History size={30} /><h2 className="serif">Your story starts here.</h2><p>Completed assessments will appear in this quiet timeline.</p></div>}</div></div>; }
function AnalysisPanel({ report }: { report?: Report }) { const results = report?.result?.disease_results?.filter((item) => item.risk !== null) ?? []; return <div className="dashboard-content fade-up"><div className="analysis-panel"><HeartPulse size={30} /><span className="eyebrow">Evidence review</span><h2 className="serif">{report?.label ?? "Choose an assessment from history."}</h2><p>{report ? "These signals are model estimates to support a conversation with a qualified clinician, not a diagnosis." : "Completed assessments will appear here with their supporting evidence."}</p>{results.map((item) => <div className="analysis-row" key={item.display_name}><span>{item.display_name}</span><strong>{Math.round((item.risk ?? 0) * 100)}%</strong></div>)}</div></div>; }
function SettingsPanel({ profile, setProfile, save }: { profile: Profile; setProfile: React.Dispatch<React.SetStateAction<Profile>>; save: (event: React.FormEvent) => void }) { return <div className="dashboard-content fade-up"><form className="settings-form" onSubmit={save}><div className="settings-section"><div><span className="eyebrow">Profile</span><h2 className="serif">A few details, when you are ready.</h2><p>Your Clerk account is the source of truth for sign-in and your name.</p></div><div className="field-stack"><label>Username<input value={profile.username} onChange={(event) => setProfile({ ...profile, username: event.target.value })} placeholder="How should we call you?" /></label><label>Phone number<input value={profile.phone} onChange={(event) => setProfile({ ...profile, phone: event.target.value })} placeholder="Optional" /></label><label>Address<textarea value={profile.address} onChange={(event) => setProfile({ ...profile, address: event.target.value })} placeholder="Optional" rows={3} /></label></div></div><button className="coral-button" type="submit">Save settings <Check size={16} /></button></form></div>; }
